# Generated by Django 3.1.7 on 2021-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0002_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='PENDING',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('ZREA:LIZOWANE', 'ZREALIZOWANE'), ('FAKTURA', 'FAKTURA')], max_length=100),
        ),
    ]
