# Generated by Django 3.1.7 on 2021-03-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0003_auto_20210318_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='NUMER_ZAMOWIENIA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='PENDING',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('ZREA:LIZOWANE', 'ZREALIZOWANE'), ('FAKTURA', 'FAKTURA'), ('SPOKO', 'FsssAKTURA')], max_length=100),
        ),
    ]
