# Generated by Django 3.1.7 on 2021-03-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0004_auto_20210318_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='ZAMAWIAJACY',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
