# Generated by Django 3.1.7 on 2021-03-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0005_transport_zamawiajacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='CAŁOPOJAZDOWE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='HANDLOWIEC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='SPEDYCJA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
