# Generated by Django 3.1.7 on 2021-03-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0008_auto_20210318_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='ILOSC_M2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
    ]
