# Generated by Django 3.1.7 on 2021-03-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0009_transport_ilosc_m2'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='FABRYKA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='OPIS',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='HANDLOWIEC',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='ILOSC_M2',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
