# Generated by Django 3.1.7 on 2021-03-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0011_auto_20210318_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='WALUTA',
        ),
    ]
