# Generated by Django 3.1.7 on 2021-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0012_remove_transport_waluta'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='WALUTA',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
