# Generated by Django 3.1.7 on 2021-03-18 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0014_remove_transport_waluta'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='WALUTA',
            field=models.ForeignKey(max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='RaportTransportowy.waluta'),
        ),
    ]
