# Generated by Django 3.1.7 on 2021-03-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0016_auto_20210318_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='FABRYKA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RaportTransportowy.fabryka'),
        ),
    ]
