# Generated by Django 3.1.7 on 2021-03-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0017_transport_fabryka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAZWA_STATUSU', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='transport',
            name='ILOSC_M2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='OPIS',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='WALUTA',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='RaportTransportowy.waluta'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='PENDING',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RaportTransportowy.status'),
        ),
    ]
