# Generated by Django 3.1.7 on 2021-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0018_auto_20210318_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='CIAGNIK',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='DATA_ROZLADUNKU',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='DATA_ZALADUNKU',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='NACZEPA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='PLANOWANA_DATA_ZALADUNKU',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='STAWKA_WYJSCIOWA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='STAWKA_WYNEGOCJOWANA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='TRASA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
