# Generated by Django 3.1.7 on 2021-03-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0019_auto_20210318_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handlowiec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAZWA_HANDLOWCA', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pobrane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAZWA_POBRANE', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='transport',
            name='DATA_DOSTARCZENIA_DOKUMENTU_TRANSPORTOWEGO',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='DATA_WYSLANIA_SKANU_FAKTURY',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='DATA_WYSTAWIENIA_FAKTURY',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='FS',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='ILOSC_FAKTUR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='NUMER_LISTU_PRZEWOZOWEGO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='POBRANE',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='RaportTransportowy.pobrane'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='HANDLOWIEC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RaportTransportowy.handlowiec'),
        ),
    ]
