# Generated by Django 3.1.7 on 2021-03-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0020_auto_20210318_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='HANDLOWIEC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
