# Generated by Django 3.1.7 on 2021-03-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0023_remove_transport_handlowiec'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='HANDLOWIEC',
            field=models.TextField(blank=True, null=True),
        ),
    ]
