# Generated by Django 3.1.7 on 2021-03-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0024_transport_handlowiec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='HANDLOWIEC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RaportTransportowy.handlowiec'),
        ),
    ]
