# Generated by Django 3.1.7 on 2021-03-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0025_auto_20210318_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='ILOSC_FAKTUR',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
