# Generated by Django 3.1.7 on 2021-03-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0027_transport_ilosc_palet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='TRASA',
        ),
        migrations.AddField(
            model_name='transport',
            name='ROZLADUNEK',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='ZALADUNEK',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
