# Generated by Django 3.1.7 on 2021-03-20 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0029_auto_20210320_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='SPEDYCJA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RaportTransportowy.spedycja'),
        ),
    ]
