# Generated by Django 3.1.7 on 2021-03-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0031_auto_20210320_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='PENDING',
        ),
    ]
