# Generated by Django 3.1.7 on 2021-03-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0032_remove_transport_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='PENDING',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RaportTransportowy.status'),
        ),
    ]
