# Generated by Django 3.1.7 on 2021-03-20 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0033_transport_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='FABRYKA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RaportTransportowy.fabryka'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='HANDLOWIEC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RaportTransportowy.handlowiec'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='POBRANE',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RaportTransportowy.pobrane'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='SPEDYCJA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RaportTransportowy.spedycja'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='WALUTA',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RaportTransportowy.waluta'),
        ),
    ]
