# Generated by Django 3.1.7 on 2021-03-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0034_auto_20210320_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabryka',
            options={'verbose_name_plural': 'Fabryki'},
        ),
        migrations.AlterModelOptions(
            name='handlowiec',
            options={'verbose_name_plural': 'Handlowcy'},
        ),
        migrations.AlterModelOptions(
            name='spedycja',
            options={'verbose_name_plural': 'Spedycje'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statusy'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name_plural': '!Transporty!'},
        ),
        migrations.AlterModelOptions(
            name='waluta',
            options={'verbose_name_plural': 'Waluty'},
        ),
    ]
