# Generated by Django 3.1.7 on 2021-03-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0040_auto_20210323_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='CAŁOPOJAZDOWE',
        ),
    ]
