# Generated by Django 3.1.7 on 2021-03-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0041_remove_transport_całopojazdowe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calopojazdowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAZWA_CALOPOJAZDOWE', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'CALOPOJAZDOWE',
            },
        ),
        migrations.AddField(
            model_name='transport',
            name='CALOPOJAZDOWE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RaportTransportowy.calopojazdowe'),
        ),
    ]
