# Generated by Django 3.1.7 on 2021-03-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0042_auto_20210323_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calopojazdowe',
            options={'verbose_name_plural': 'Całopojazdowe?'},
        ),
        migrations.AlterModelOptions(
            name='zamawiajacy',
            options={'verbose_name_plural': 'Zamawiający'},
        ),
        migrations.RemoveField(
            model_name='transport',
            name='DATA_DOSTARCZENIA_DOKUMENTU_TRANSPORTOWEGO',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='NUMER_ZAMOWIENIA',
        ),
    ]
