# Generated by Django 3.1.7 on 2021-04-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0044_auto_20210330_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pobrane',
            options={'verbose_name_plural': 'Pobrane'},
        ),
    ]
