# Generated by Django 3.1.7 on 2021-04-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0045_auto_20210415_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pobrane',
            options={},
        ),
        migrations.AddField(
            model_name='transport',
            name='NAZWA_HANDLOWCA',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='NAZWA_KLIENTA',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='NUMER_ZALADUNKOWY',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='OPIS_POLACZONYCH',
            field=models.TextField(blank=True, null=True),
        ),
    ]
