# Generated by Django 3.1.7 on 2021-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaportTransportowy', '0046_auto_20210415_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='MIESIAC',
            field=models.CharField(blank=True, choices=[('1.styczen', '1.styczen'), ('2.luty', '2.luty'), ('3.marzec', '3.marzec'), ('4.kwiecień', '4.kwiecień'), ('5.maj', '5.maj'), ('6.czerwiec', '6.czerwiec'), ('7.lipiec', '7.lipiec'), ('8.sierpień', '8.sierpirń'), ('9.wrzesień', '9.wrzesień'), ('10.październik', '10.październik'), ('11.listopad', '11.listopad'), ('12.grudzień', '12.grudzień')], max_length=20, null=True),
        ),
    ]
